[package]
name = "lumenply-io"
description = "Image codecs and colour conversion"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
lumenply-tiles.workspace = true
image.workspace = true
thiserror.workspace = true
lumenply-doc.workspace = true
serde.workspace = true
serde_json.workspace = true
zip.workspace = true
flate2.workspace = true
png.workspace = true
quick-xml.workspace = true
exr.workspace = true
qcms.workspace = true
rawler = "0.7.0"
image-webp = "0.2"
gif = "0.13"
color_quant = "1.1"

lumenply-render.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2-core-foundation = { version = "0.3", default-features = false, features = ["std", "CFURL", "CFDictionary", "CFNumber", "CFString", "CFCGTypes"] }
objc2-core-graphics = { version = "0.3", default-features = false, features = ["std", "CGBitmapContext", "CGColorSpace", "CGContext", "CGImage"] }
objc2-image-io = { version = "0.3", default-features = false, features = ["std", "CGImageSource", "objc2-core-graphics"] }
